from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e60dd9daf95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('profile_photo_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('audit_log_actor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_pkey'))
    )
    op.create_index('idx_audit_log_actor', 'audit_log', ['actor_id'], unique=False)
    op.create_index('idx_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('batches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('batches_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('batches_pkey'))
    )
    op.create_table('token_blacklist',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('jti', sa.Text(), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('token_blacklist_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey')),
    sa.UniqueConstraint('jti', name=op.f('token_blacklist_jti_key'))
    )
    op.create_index('idx_token_blacklist_expires', 'token_blacklist', ['expires_at'], unique=False)
    op.create_table('albums',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'deleted', name='album_status'), server_default='pending', nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('date_end IS NULL OR date_end >= date_start', name='albums_check'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('albums_batch_id_fkey')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('albums_created_by_fkey')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('albums_reviewed_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('albums_pkey'))
    )
    op.create_index('idx_albums_batch_status', 'albums', ['batch_id', 'status'], unique=False)
    op.create_index('idx_albums_month_day', 'albums', [sa.literal_column('EXTRACT(month FROM date_start)'), sa.literal_column('EXTRACT(day FROM date_start)')], unique=False)
    op.create_table('batch_memberships',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('member', 'batch_admin', name='batch_role'), server_default='member', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('batch_memberships_batch_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('batch_memberships_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('batch_memberships_pkey')),
    sa.UniqueConstraint('user_id', 'batch_id', name=op.f('batch_memberships_user_id_batch_id_key'))
    )
    op.create_index('idx_batch_memberships_batch', 'batch_memberships', ['batch_id'], unique=False)
    op.create_index('idx_batch_memberships_user', 'batch_memberships', ['user_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('album_id', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('photos_album_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('photos_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('photos_pkey'))
    )
    op.create_index('idx_photos_album', 'photos', ['album_id'], unique=False)
    op.create_index('idx_photos_uploaded_by', 'photos', ['uploaded_by'], unique=False)
    op.create_table('photo_likes',
    sa.Column('photo_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name=op.f('photo_likes_photo_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('photo_likes_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id', 'user_id', name=op.f('photo_likes_pkey'))
    )
    op.create_index('idx_photo_likes_user', 'photo_likes', ['user_id'], unique=False)
    op.create_table('stories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('album_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('pinned_photo_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('stories_album_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('stories_author_id_fkey')),
    sa.ForeignKeyConstraint(['pinned_photo_id'], ['photos.id'], name=op.f('stories_pinned_photo_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('stories_pkey'))
    )
    op.create_index('idx_stories_album', 'stories', ['album_id'], unique=False)
    op.create_table('story_likes',
    sa.Column('story_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('story_likes_story_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('story_likes_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('story_id', 'user_id', name=op.f('story_likes_pkey'))
    )
    op.create_index('idx_story_likes_user', 'story_likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_story_likes_user', table_name='story_likes')
    op.drop_table('story_likes')
    op.drop_index('idx_stories_album', table_name='stories')
    op.drop_table('stories')
    op.drop_index('idx_photo_likes_user', table_name='photo_likes')
    op.drop_table('photo_likes')
    op.drop_index('idx_photos_uploaded_by', table_name='photos')
    op.drop_index('idx_photos_album', table_name='photos')
    op.drop_table('photos')
    op.drop_index('idx_batch_memberships_user', table_name='batch_memberships')
    op.drop_index('idx_batch_memberships_batch', table_name='batch_memberships')
    op.drop_table('batch_memberships')
    op.drop_index('idx_albums_month_day', table_name='albums')
    op.drop_index('idx_albums_batch_status', table_name='albums')
    op.drop_table('albums')
    op.drop_index('idx_token_blacklist_expires', table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_table('batches')
    op.drop_index('idx_audit_log_entity', table_name='audit_log')
    op.drop_index('idx_audit_log_actor', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    # ### end Alembic commands ###
    # Manual: ENUM types outlive the tables that used them.
    sa.Enum(name='batch_role').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='album_status').drop(op.get_bind(), checkfirst=True)
